### ISSUE TITLE
Error running example "models_waving_cubes.lua"

### ISSUE THREAD

**Issue by adamlwgriffiths** [Rabios/raylua#2]
**Describe the bug**
The models_waving_cubes.lua example references the `ffi` module, but does not import it.
`... rl.ColorFromHSV(ffi.new("Vector3", ...`

**To Reproduce**
lua models_waving_cubes.lua

```
lua: models_waving_cubes.lua:40: missing declaration for symbol 'ffi'
stack traceback:
	[C]: in function '__index'
	models_waving_cubes.lua:40: in main chunk
	[C]: at 0x004061b0
```

Adding a `local ff = require("ffi")` results in this error

```
lua: models_waving_cubes.lua:41: bad argument #1 to 'ColorFromHSV' (cannot convert 'struct Vector3' to 'float')
stack traceback:
	[C]: in function 'ColorFromHSV'
	models_waving_cubes.lua:41: in main chunk
	[C]: at 0x004061b0
```

**Desktop (please complete the following information):**
 - OS: NixOS

**Comment by Rabios** [comment]
@adamlwgriffiths Fixed now, Thanks!
