### ISSUE TITLE
Raygui not functional

### ISSUE THREAD

**Issue by adamlwgriffiths** [Rabios/raylua#3]
It appears that the `raygui.lua` module is not functional.

Unlike raylib, raygui is a header-only library.
This means the [return at the bottom of raygui.lua](https://github.com/Rabios/raylua/blob/master/raygui.lua#L386) is incorrect, as there is no library.

**Comment by adamlwgriffiths** [comment]
So from what I can tell, tsnake's raylua library has a custom .c file that includes raygui, physac, etc.
This is compiled and then is what you pass to `ffi.load`.

There's very little documentation about this, most of these repos contain pre-compiled dlls.
I'll see if I can get something working.

**Comment by Rabios** [comment]
First you need to build shared lib version of raygui via C compiler (dll/so/dylib)
Second, Include raylib then raygui in your Lua code

Being honest, I haven't tested raygui at time i uploaded it cause didn't had time for that!

Thanks for your contribution to raylua, Really appreciate that ❤️ !

**Comment by adamlwgriffiths** [comment]
Do you have the .c file you used to compile raygui to a shared object?
I suspect an empty file may do the trick.

**Comment by adamlwgriffiths** [comment]
Ok, I think my problem comes down to trying to use raylib and raygui both as .so files.
I think what needs to happen is you compile raylib as a static lib (.a) and then link that and raygui into a big .so file, otherwise you end up with undefined symbols in raygui. Even though it can include the raylib header, it doesn't link against raylib so it ends up with missing symbols.

I've raised an [issue on raygui](https://github.com/raysan5/raygui/issues/143), will see if they can make things a bit easier.

**Comment by Rabios** [comment]
@adamlwgriffiths Sorry for the late reply...

You can try something like this...
(idk if works, Also please ping me cause i'm not used to read messages if not pinged...)

```c
// raygui.c
#include <raylib.h>
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_ICONS
#include "raygui.h"
```

**Comment by adamlwgriffiths** [comment]
Yeah I'm just not sure if having 2 SOs each but duplicated raylib functions will work.
I can give it a shot.

**Comment by Rabios** [comment]
That's the problem, I think you need to use `raygui.o` and `raylib.o` so i hope it works...

**Comment by Rabios** [comment]
Also, As raygui built on raylib the hardest way to get it running is to port from the C source...

> idk if can be last hope XD

**Comment by adamlwgriffiths** [comment]
It seems there are two ways to do it.
Make one giant raylib shared object.
Or create a redirection layer that implements the shared functions in raygui. Then at init time, pass the raylib shared object to these functions so they can redirect the calls over to raylib.

The latter would be a more permanent / flexible solution.
I'm just not sure I have the time or need. I'll probably move across to imgui.

At least I understand what's going on now. I'll close this and leave my issue on raygui. See if they want to do anything.
