### ISSUE TITLE
Cannot require raygui

### ISSUE THREAD

**Issue by MonkeyPanic** [Rabios/raylua#4]
trying to load raygui via:
local rl = require ("raylib")
local gui = require("raygui")
 
but I always get "cannot load module 'raygui'". Requiring raylib or other lua files works as expected, though. I feel like I am missing something important? (I am very new to raylib)

**Comment by MonkeyPanic** [comment]
ah... no... raygui is a file. have to use loadfile ... closed

**Comment by MonkeyPanic** [comment]
oh, I have to build a shared lib. didn't see that line, nvm

**Comment by Rabios** [comment]
Yeah, raygui shared lib is required...

I don't distribute ones because raylib releases doesn't include these, Which means that if i did it would be for just one target which i don't want to...
