### ISSUE TITLE
How to use physac and raygui?

### ISSUE THREAD

**Issue by 1MarcosDev** [Rabios/raylua#5]
This is giving me a headache. How do I use physac.lua and raygui.lua? If I have to compile something, how do I do it? I'm having a lot of problems with this.

Grateful for the answer!

**Comment by Rabios** [comment]
Hi, Sorry for late reply as i'm really busy...

Make sure you have C compiler, Create a C file for raygui with following:

```c
/* raygui.c */
#include <raylib.h> /* or "raylib.h" */
#define RAYGUI_IMPLEMENTATION 1
#include "raygui.h"
```

Grab raylib static library from one of the raylib releases...

Then compile raygui into shared library, Like this way:

```sh
gcc -shared raygui.c -o raygui.dll -lraylib
```

Then require raygui and i believe it should works...

**Comment by 1MarcosDev** [comment]
Thanks for the reply, and congratulations on the amazing work! Thanks for sharing raylua!
