### ISSUE TITLE
Raylua error

### ISSUE THREAD

**Issue by Yaumama** [Rabios/raylua#9]
**Describe the bug**
In raylib.lua, I get an error called that says `.\raylua-master/raylib.lua:2353: cannot load module 'libraylib64.dll': The specified module could not be found.` I don't know why this is happening because `libraylib64.dll` is in the same folder as `raylib.lua`.

**To Reproduce**
1. Download the raylua github zip file
2. Extract the zip file to the project root
3. Paste in the new window example into main.lua in the project root file but replace `require("raylib")` with `require("raylua-master/raylib")`
4. Run `luajit main.lua` in the terminal
5. See the error

**Expected behavior**
I expected a window to pop up

**Screenshots**
![image](https://user-images.githubusercontent.com/83031256/155828849-8c77a8e7-1b58-4925-bf71-0fdfedd2c231.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Browser version: 98.0.4758.102
 - OS version: Windows 11

**Additional context**
Here is the code:
```lua
local rl = require("raylua-master/raylib")

local screenWidth = 800
local screenHeight = 450

rl.InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window")
rl.SetTargetFPS(60)

while not rl.WindowShouldClose() do
  rl.BeginDrawing()
  rl.ClearBackground(rl.RAYWHITE)
  rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.LIGHTGRAY)
  rl.EndDrawing()
end

rl.CloseWindow()
```

**Comment by Rabios** [comment]
LuaJIT loads shared libraries from working directory, So run the example inside `raylua-master` folder from your terminal...

That's because LuaJIT FFI dynamic lib/object loading mechanism is based on dlsym and other dynamic loading functions...

**Comment by Yaumama** [comment]
Thank you so much it worked!

**Comment by Rabios** [comment]
OK closing the issue as it worked...
